"""Domain models mirroring the `public.links`, `public.topics` and `public.link_topics` tables."""

from __future__ import annotations

from datetime import datetime
from typing import ClassVar, Literal
from uuid import UUID

from pydantic import BaseModel


class Link(BaseModel):
    __tablename__: ClassVar[str] = "links"

    id: UUID
    submitted_by: UUID | None = None
    url: str
    title: str
    description: str | None = None
    origin: Literal["local", "fediverse", "feed"]
    fediverse_post_uri: str | None = None
    thread_url: str | None = None
    image_url: str | None = None
    slug: str | None = None
    body_markdown: str | None = None
    # Generated by the database from title + host, for server-side search.
    search_text: str | None = None
    created_at: datetime


class Topic(BaseModel):
    __tablename__: ClassVar[str] = "topics"

    id: str
    name: str
    description: str
    created_at: datetime


class LinkTopic(BaseModel):
    __tablename__: ClassVar[str] = "link_topics"

    link_id: UUID
    topic_id: str
    p: float
    labeled_by: Literal["manual", "jev"]
    labeled_at: datetime
