"""Domain models mirroring the `public.links`, `public.topics`, `public.link_topics`,
`public.domain_source_types` and `public.sources` tables."""

from __future__ import annotations

from datetime import datetime
from typing import ClassVar, Literal
from uuid import UUID

from pydantic import BaseModel


class Link(BaseModel):
    __tablename__: ClassVar[str] = "links"

    id: UUID
    submitted_by: UUID | None = None
    url: str
    title: str
    description: str | None = None
    origin: Literal["local", "fediverse", "feed"]
    fediverse_post_uri: str | None = None
    thread_url: str | None = None
    image_url: str | None = None
    author: str | None = None
    slug: str | None = None
    body_markdown: str | None = None
    # Generated by the database from title + host, for server-side search.
    search_text: str | None = None
    created_at: datetime


class Topic(BaseModel):
    __tablename__: ClassVar[str] = "topics"

    id: str
    name: str
    description: str
    created_at: datetime


class LinkTopic(BaseModel):
    __tablename__: ClassVar[str] = "link_topics"

    link_id: UUID
    topic_id: str
    p: float
    labeled_by: Literal["manual", "jev"]
    labeled_at: datetime


class DomainSourceType(BaseModel):
    __tablename__: ClassVar[str] = "domain_source_types"

    domain: str
    source_type: Literal["mainstream_media", "youtube_longform"]
    created_at: datetime


class Source(BaseModel):
    __tablename__: ClassVar[str] = "sources"

    id: UUID
    kind: Literal["youtube_channel", "mastodon_account"]
    identifier: str
    label: str | None = None
    enabled: bool
    created_at: datetime
