-- Every profile with a handle is also a fediverse account, @handle@<site
-- host>, and its replies on the site's federated posts are sent out as that
-- account's replies.

-- Deployment-specific addresses live here rather than in code, filled in
-- per environment (not by a migration): site_origin (the public site, e.g.
-- https://example.org), site_actor_username (the site account's
-- username) and functions_url (the Supabase project's /functions/v1 base).
-- service_role only; SQL reads it through app_setting().
create table public.app_settings (
  key text primary key,
  value text not null
);

alter table public.app_settings enable row level security;
revoke all on public.app_settings from anon, authenticated;

create function public.app_setting(setting text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select value from public.app_settings where key = setting
$$;

revoke execute on function public.app_setting(text) from public, anon, authenticated;
grant execute on function public.app_setting(text) to service_role;

-- Earlier migrations wrote the site's and the functions' addresses inline;
-- these replace them with the settings above.
create or replace function public.ap_posts_request_delivery()
returns trigger
language plpgsql
security definer
set search_path = public, net
as $$
begin
  perform net.http_post(
    url := public.app_setting('functions_url') || '/activitypub/ap/deliver',
    body := '{}'::jsonb,
    headers := '{"Content-Type": "application/json"}'::jsonb
  );
  return null;
end;
$$;

create or replace function public.publish_post(content text)
returns uuid
language plpgsql
set search_path = public
as $$
declare
  new_id uuid := gen_random_uuid();
  site text := public.app_setting('site_origin');
begin
  insert into public.links (id, url, title, origin, author)
  values (
    new_id,
    site || '/p/' || new_id,
    content,
    'local',
    '@' || public.app_setting('site_actor_username') || '@' || regexp_replace(site, '^https?://', '')
  );
  insert into public.ap_posts (link_id) values (new_id);
  return new_id;
end;
$$;

-- Handles become fediverse usernames, so they're limited to the characters
-- every server accepts. (They were already unique.)
alter table public.profiles
  add constraint profiles_handle_format check (handle ~ '^[a-z0-9_]{1,30}$');

-- Each account's own signing keypair, generated by the activitypub edge
-- function the first time the account is needed. Only service_role reads it.
create table public.ap_actor_keys (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  public_key_pem text not null,
  private_key_pem text not null,
  created_at timestamptz not null default now()
);

alter table public.ap_actor_keys enable row level security;
revoke all on public.ap_actor_keys from anon, authenticated;

-- A remote actor can now follow the site actor (profile_id null) or any
-- profile's account.
alter table public.ap_followers
  add column profile_id uuid references public.profiles(id) on delete cascade,
  drop constraint ap_followers_actor_url_key,
  add constraint ap_followers_actor_url_profile_id_key unique nulls not distinct (actor_url, profile_id);

-- Where to send a reply so the remote people already in a conversation see it.
alter table public.remote_actors
  add column inbox_url text,
  add column shared_inbox_url text;

-- What happened to a local reply on the fediverse: 'sent' as the author's
-- reply, or 'local' (not on a federated post, no usable handle, or over the
-- rate limit). Null until the edge function has looked at it.
alter table public.replies
  add column ap_state text check (ap_state in ('sent', 'local'));

-- Local replies wait for a decision; replies that came from the fediverse
-- are already there.
update public.replies set ap_state = 'local' where author_id is not null;

-- Decides every pending local reply in one statement, so two concurrent calls
-- never send one twice, and returns them for the function to deliver.
create function public.claim_federated_replies(handle_pattern text, reserved_handle text, per_hour integer)
returns table (id uuid, link_id uuid, author_id uuid, handle text, body text, created_at timestamptz, ap_state text)
language sql
set search_path = public
as $$
  update public.replies r
  set ap_state = case
    when exists (select 1 from public.ap_posts p where p.link_id = r.link_id)
      and pr.handle ~ handle_pattern
      and pr.handle <> reserved_handle
      and (select count(*) from public.replies s
           where s.author_id = r.author_id and s.ap_state = 'sent'
             and s.created_at > now() - interval '1 hour') < per_hour
    then 'sent'
    else 'local'
  end
  from public.profiles pr
  where pr.id = r.author_id and r.ap_state is null
  returning r.id, r.link_id, r.author_id, pr.handle, r.body, r.created_at, r.ap_state
$$;

revoke execute on function public.claim_federated_replies(text, text, integer) from public, anon, authenticated;

-- security definer: replies are inserted and deleted by site users through
-- RLS, and those roles can't call pg_net themselves.
create function public.replies_request_delivery()
returns trigger
language plpgsql
security definer
set search_path = public, net
as $$
begin
  perform net.http_post(
    url := public.app_setting('functions_url') || '/activitypub/ap/deliver-replies',
    body := '{}'::jsonb,
    headers := '{"Content-Type": "application/json"}'::jsonb
  );
  return null;
end;
$$;

create trigger replies_request_delivery
  after insert on public.replies
  for each statement
  execute function public.replies_request_delivery();

-- A sent reply deleted on the site is deleted on the fediverse too. The row
-- is gone by then, so the trigger passes along what the function needs.
create function public.replies_request_remote_delete()
returns trigger
language plpgsql
security definer
set search_path = public, net
as $$
begin
  perform net.http_post(
    url := public.app_setting('functions_url') || '/activitypub/ap/delete-reply',
    body := jsonb_build_object('reply_id', old.id, 'author_id', old.author_id, 'link_id', old.link_id),
    headers := '{"Content-Type": "application/json"}'::jsonb
  );
  return null;
end;
$$;

create trigger replies_request_remote_delete
  after delete on public.replies
  for each row
  when (old.ap_state = 'sent')
  execute function public.replies_request_remote_delete();

revoke execute on function public.replies_request_delivery() from public, anon, authenticated;
revoke execute on function public.replies_request_remote_delete() from public, anon, authenticated;
