-- entities: the organisations articles are about (NLCabs, Uber, a co-op), each
-- classified by what it does in NACE Rev. 2.1, the EU's statistical
-- classification of economic activities (Regulation (EU) 2023/137). Topics say
-- what an article is about; an entity's NACE code says what kind of business
-- it covers. NACE 2.1 separates platforms from the service they broker: a
-- ride-hailing app is 52.32 (intermediation for passenger transportation), a
-- taxi operator 49.33. Public-read, service_role-write like topics.
create table public.nace_activities (
  code text primary key check (code ~ '^([A-V]|[0-9]{2}|[0-9]{2}\.[0-9]|[0-9]{2}\.[0-9]{2})$'),
  level smallint not null check (level between 1 and 4),
  parent_code text references public.nace_activities(code),
  title text not null,
  check ((level = 1) = (parent_code is null))
);

create table public.entities (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  kind text not null check (kind in ('company', 'cooperative', 'nonprofit', 'public_body')),
  nace_code text references public.nace_activities(code),
  country text check (country ~ '^[A-Z]{2}$'),
  wikidata_id text unique check (wikidata_id ~ '^Q[1-9][0-9]*$'),
  website text check (website ~ '^https://'),
  description text,
  created_at timestamptz not null default now()
);

create table public.link_entities (
  link_id uuid not null references public.links(id) on delete cascade,
  entity_id uuid not null references public.entities(id) on delete cascade,
  primary key (link_id, entity_id)
);

create index link_entities_entity_id_idx on public.link_entities (entity_id);

alter table public.nace_activities enable row level security;
alter table public.entities enable row level security;
alter table public.link_entities enable row level security;

create policy "nace activities are publicly readable"
  on public.nace_activities for select to anon, authenticated using (true);
create policy "entities are publicly readable"
  on public.entities for select to anon, authenticated using (true);
create policy "link entities are publicly readable"
  on public.link_entities for select to anon, authenticated using (true);

revoke insert, update, delete, truncate on public.nace_activities, public.entities, public.link_entities
  from anon, authenticated;

-- Source: the NACE Rev. 2.1 structure as published on EUR-Lex, via
-- github.com/jnsprnw/nace-codes (data/source/codes-2.1.csv).
insert into public.nace_activities (code, level, parent_code, title) values
  ('A', 1, NULL, 'Agriculture, forestry and fishing'),
  ('B', 1, NULL, 'Mining and quarrying'),
  ('C', 1, NULL, 'Manufacturing'),
  ('D', 1, NULL, 'Electricity, gas, steam and air conditioning supply'),
  ('E', 1, NULL, 'Water supply; sewerage, waste management and remediation activities'),
  ('F', 1, NULL, 'Construction'),
  ('G', 1, NULL, 'Wholesale and retail trade'),
  ('H', 1, NULL, 'Transportation and storage'),
  ('I', 1, NULL, 'Accommodation and food service activities'),
  ('J', 1, NULL, 'Publishing, broadcasting, and content production and distribution activities'),
  ('K', 1, NULL, 'Telecommunication, computer programming, consulting, computing infrastructure and other information service activities'),
  ('L', 1, NULL, 'Financial and insurance activities'),
  ('M', 1, NULL, 'Real estate activities'),
  ('N', 1, NULL, 'Professional, scientific and technical activities'),
  ('O', 1, NULL, 'Administrative and support service activities'),
  ('P', 1, NULL, 'Public administration and defence; compulsory social security'),
  ('Q', 1, NULL, 'Education'),
  ('R', 1, NULL, 'Human health and social work activities'),
  ('S', 1, NULL, 'Arts, sports and recreation'),
  ('T', 1, NULL, 'Other service activities'),
  ('U', 1, NULL, 'Activities of households as employers and undifferentiated goods – and service-producing activities of households for own use'),
  ('V', 1, NULL, 'Activities of extraterritorial organisations and bodies'),
  ('01', 2, 'A', 'Crop and animal production, hunting and related service activities'),
  ('01.1', 3, '01', 'Growing of non-perennial crops'),
  ('01.11', 4, '01.1', 'Growing of cereals, other than rice, leguminous crops and oil seeds'),
  ('01.12', 4, '01.1', 'Growing of rice'),
  ('01.13', 4, '01.1', 'Growing of vegetables and melons, roots and tubers'),
  ('01.14', 4, '01.1', 'Growing of sugar cane'),
  ('01.15', 4, '01.1', 'Growing of tobacco'),
  ('01.16', 4, '01.1', 'Growing of fibre crops'),
  ('01.19', 4, '01.1', 'Growing of other non-perennial crops'),
  ('01.2', 3, '01', 'Growing of perennial crops'),
  ('01.21', 4, '01.2', 'Growing of grapes'),
  ('01.22', 4, '01.2', 'Growing of tropical and subtropical fruits'),
  ('01.23', 4, '01.2', 'Growing of citrus fruits'),
  ('01.24', 4, '01.2', 'Growing of pome fruits and stone fruits'),
  ('01.25', 4, '01.2', 'Growing of other tree and bush fruits and nuts'),
  ('01.26', 4, '01.2', 'Growing of oleaginous fruits'),
  ('01.27', 4, '01.2', 'Growing of beverage crops'),
  ('01.28', 4, '01.2', 'Growing of spices, aromatic, drug and pharmaceutical crops'),
  ('01.29', 4, '01.2', 'Growing of other perennial crops'),
  ('01.3', 3, '01', 'Plant propagation'),
  ('01.30', 4, '01.3', 'Plant propagation'),
  ('01.4', 3, '01', 'Animal production'),
  ('01.41', 4, '01.4', 'Raising of dairy cattle'),
  ('01.42', 4, '01.4', 'Raising of other cattle and buffaloes'),
  ('01.43', 4, '01.4', 'Raising of horses and other equines'),
  ('01.44', 4, '01.4', 'Raising of camels and camelids'),
  ('01.45', 4, '01.4', 'Raising of sheep and goats'),
  ('01.46', 4, '01.4', 'Raising of swine and pigs'),
  ('01.47', 4, '01.4', 'Raising of poultry'),
  ('01.48', 4, '01.4', 'Raising of other animals'),
  ('01.5', 3, '01', 'Mixed farming'),
  ('01.50', 4, '01.5', 'Mixed farming'),
  ('01.6', 3, '01', 'Support activities to agriculture and post-harvest crop activities'),
  ('01.61', 4, '01.6', 'Support activities for crop production'),
  ('01.62', 4, '01.6', 'Support activities for animal production'),
  ('01.63', 4, '01.6', 'Post-harvest crop activities and seed processing for propagation'),
  ('01.7', 3, '01', 'Hunting, trapping and related service activities'),
  ('01.70', 4, '01.7', 'Hunting, trapping and related service activities'),
  ('02', 2, 'A', 'Forestry and logging'),
  ('02.1', 3, '02', 'Silviculture and other forestry activities'),
  ('02.10', 4, '02.1', 'Silviculture and other forestry activities'),
  ('02.2', 3, '02', 'Logging'),
  ('02.20', 4, '02.2', 'Logging'),
  ('02.3', 3, '02', 'Gathering of wild growing non-wood products'),
  ('02.30', 4, '02.3', 'Gathering of wild growing non-wood products'),
  ('02.4', 3, '02', 'Support services to forestry'),
  ('02.40', 4, '02.4', 'Support services to forestry'),
  ('03', 2, 'A', 'Fishing and aquaculture'),
  ('03.1', 3, '03', 'Fishing'),
  ('03.11', 4, '03.1', 'Marine fishing'),
  ('03.12', 4, '03.1', 'Freshwater fishing'),
  ('03.2', 3, '03', 'Aquaculture'),
  ('03.21', 4, '03.2', 'Marine aquaculture'),
  ('03.22', 4, '03.2', 'Freshwater aquaculture'),
  ('03.3', 3, '03', 'Support activities for fishing and aquaculture'),
  ('03.30', 4, '03.3', 'Support activities for fishing and aquaculture'),
  ('05', 2, 'B', 'Mining of coal and lignite'),
  ('05.1', 3, '05', 'Mining of hard coal'),
  ('05.10', 4, '05.1', 'Mining of hard coal'),
  ('05.2', 3, '05', 'Mining of lignite'),
  ('05.20', 4, '05.2', 'Mining of lignite'),
  ('06', 2, 'B', 'Extraction of crude petroleum and natural gas'),
  ('06.1', 3, '06', 'Extraction of crude petroleum'),
  ('06.10', 4, '06.1', 'Extraction of crude petroleum'),
  ('06.2', 3, '06', 'Extraction of natural gas'),
  ('06.20', 4, '06.2', 'Extraction of natural gas'),
  ('07', 2, 'B', 'Mining of metal ores'),
  ('07.1', 3, '07', 'Mining of iron ores'),
  ('07.10', 4, '07.1', 'Mining of iron ores'),
  ('07.2', 3, '07', 'Mining of non-ferrous metal ores'),
  ('07.21', 4, '07.2', 'Mining of uranium and thorium ores'),
  ('07.29', 4, '07.2', 'Mining of other non-ferrous metal ores'),
  ('08', 2, 'B', 'Other mining and quarrying'),
  ('08.1', 3, '08', 'Quarrying of stone, sand and clay'),
  ('08.11', 4, '08.1', 'Quarrying of ornamental stone, limestone, gypsum, slate and other stone'),
  ('08.12', 4, '08.1', 'Operation of gravel and sand pits and mining of clay and kaolin'),
  ('08.9', 3, '08', 'Mining and quarrying n.e.c.'),
  ('08.91', 4, '08.9', 'Mining of chemical and fertiliser minerals'),
  ('08.92', 4, '08.9', 'Extraction of peat'),
  ('08.93', 4, '08.9', 'Extraction of salt'),
  ('08.99', 4, '08.9', 'Other mining and quarrying n.e.c.'),
  ('09', 2, 'B', 'Mining support service activities'),
  ('09.1', 3, '09', 'Support activities for petroleum and natural gas extraction'),
  ('09.10', 4, '09.1', 'Support activities for petroleum and natural gas extraction'),
  ('09.9', 3, '09', 'Support activities for other mining and quarrying'),
  ('09.90', 4, '09.9', 'Support activities for other mining and quarrying'),
  ('10', 2, 'C', 'Manufacture of food products'),
  ('10.1', 3, '10', 'Processing and preserving of meat and production of meat products'),
  ('10.11', 4, '10.1', 'Processing and preserving of meat, except of poultry meat'),
  ('10.12', 4, '10.1', 'Processing and preserving of poultry meat'),
  ('10.13', 4, '10.1', 'Production of meat and poultry meat products'),
  ('10.2', 3, '10', 'Processing and preserving of fish, crustaceans and molluscs'),
  ('10.20', 4, '10.2', 'Processing and preserving of fish, crustaceans and molluscs'),
  ('10.3', 3, '10', 'Processing and preserving of fruit and vegetables'),
  ('10.31', 4, '10.3', 'Processing and preserving of potatoes'),
  ('10.32', 4, '10.3', 'Manufacture of fruit and vegetable juice'),
  ('10.39', 4, '10.3', 'Other processing and preserving of fruit and vegetables'),
  ('10.4', 3, '10', 'Manufacture of vegetable and animal oils and fats'),
  ('10.41', 4, '10.4', 'Manufacture of oils and fats'),
  ('10.42', 4, '10.4', 'Manufacture of margarine and similar edible fats'),
  ('10.5', 3, '10', 'Manufacture of dairy products and edible ice'),
  ('10.51', 4, '10.5', 'Manufacture of dairy products'),
  ('10.52', 4, '10.5', 'Manufacture of ice cream and other edible ice'),
  ('10.6', 3, '10', 'Manufacture of grain mill products, starches and starch products'),
  ('10.61', 4, '10.6', 'Manufacture of grain mill products'),
  ('10.62', 4, '10.6', 'Manufacture of starches and starch products'),
  ('10.7', 3, '10', 'Manufacture of bakery and farinaceous products'),
  ('10.71', 4, '10.7', 'Manufacture of bread; manufacture of fresh pastry goods and cakes'),
  ('10.72', 4, '10.7', 'Manufacture of rusks, biscuits, preserved pastries and cakes'),
  ('10.73', 4, '10.7', 'Manufacture of farinaceous products'),
  ('10.8', 3, '10', 'Manufacture of other food products'),
  ('10.81', 4, '10.8', 'Manufacture of sugar'),
  ('10.82', 4, '10.8', 'Manufacture of cocoa, chocolate and sugar confectionery'),
  ('10.83', 4, '10.8', 'Processing of tea and coffee'),
  ('10.84', 4, '10.8', 'Manufacture of condiments and seasonings'),
  ('10.85', 4, '10.8', 'Manufacture of prepared meals and dishes'),
  ('10.86', 4, '10.8', 'Manufacture of homogenised food preparations and dietetic food'),
  ('10.89', 4, '10.8', 'Manufacture of other food products n.e.c.'),
  ('10.9', 3, '10', 'Manufacture of prepared animal feeds'),
  ('10.91', 4, '10.9', 'Manufacture of prepared feeds for farm animals'),
  ('10.92', 4, '10.9', 'Manufacture of prepared pet foods'),
  ('11', 2, 'C', 'Manufacture of beverages'),
  ('11.0', 3, '11', 'Manufacture of beverages'),
  ('11.01', 4, '11.0', 'Distilling, rectifying and blending of spirits'),
  ('11.02', 4, '11.0', 'Manufacture of wine from grape'),
  ('11.03', 4, '11.0', 'Manufacture of cider and other fermented fruit beverages'),
  ('11.04', 4, '11.0', 'Manufacture of other non-distilled fermented beverages'),
  ('11.05', 4, '11.0', 'Manufacture of beer'),
  ('11.06', 4, '11.0', 'Manufacture of malt'),
  ('11.07', 4, '11.0', 'Manufacture of soft drinks and bottled waters'),
  ('12', 2, 'C', 'Manufacture of tobacco products'),
  ('12.0', 3, '12', 'Manufacture of tobacco products'),
  ('12.00', 4, '12.0', 'Manufacture of tobacco products'),
  ('13', 2, 'C', 'Manufacture of textiles'),
  ('13.1', 3, '13', 'Preparation and spinning of textile fibres'),
  ('13.10', 4, '13.1', 'Preparation and spinning of textile fibres'),
  ('13.2', 3, '13', 'Weaving of textiles'),
  ('13.20', 4, '13.2', 'Weaving of textiles'),
  ('13.3', 3, '13', 'Finishing of textiles'),
  ('13.30', 4, '13.3', 'Finishing of textiles'),
  ('13.9', 3, '13', 'Manufacture of other textiles'),
  ('13.91', 4, '13.9', 'Manufacture of knitted and crocheted fabrics'),
  ('13.92', 4, '13.9', 'Manufacture of household textiles and made-up furnishing articles'),
  ('13.93', 4, '13.9', 'Manufacture of carpets and rugs'),
  ('13.94', 4, '13.9', 'Manufacture of cordage, rope, twine and netting'),
  ('13.95', 4, '13.9', 'Manufacture of non-wovens and non-woven articles'),
  ('13.96', 4, '13.9', 'Manufacture of other technical and industrial textiles'),
  ('13.99', 4, '13.9', 'Manufacture of other textiles n.e.c.'),
  ('14', 2, 'C', 'Manufacture of wearing apparel'),
  ('14.1', 3, '14', 'Manufacture of knitted and crocheted apparel'),
  ('14.10', 4, '14.1', 'Manufacture of knitted and crocheted apparel'),
  ('14.2', 3, '14', 'Manufacture of other wearing apparel and accessories'),
  ('14.21', 4, '14.2', 'Manufacture of outerwear'),
  ('14.22', 4, '14.2', 'Manufacture of underwear'),
  ('14.23', 4, '14.2', 'Manufacture of workwear'),
  ('14.24', 4, '14.2', 'Manufacture of leather clothes and fur apparel'),
  ('14.29', 4, '14.2', 'Manufacture of other wearing apparel and accessories n.e.c.'),
  ('15', 2, 'C', 'Manufacture of leather and related products of other materials'),
  ('15.1', 3, '15', 'Tanning, dyeing, dressing of leather and fur; manufacture of luggage, handbags, saddlery and harness'),
  ('15.11', 4, '15.1', 'Tanning, dressing, dyeing of leather and fur'),
  ('15.12', 4, '15.1', 'Manufacture of luggage, handbags, saddlery and harness of any material'),
  ('15.2', 3, '15', 'Manufacture of footwear'),
  ('15.20', 4, '15.2', 'Manufacture of footwear'),
  ('16', 2, 'C', 'Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials'),
  ('16.1', 3, '16', 'Sawmilling and planing of wood; processing and finishing of wood'),
  ('16.11', 4, '16.1', 'Sawmilling and planing of wood'),
  ('16.12', 4, '16.1', 'Processing and finishing of wood'),
  ('16.2', 3, '16', 'Manufacture of products of wood, cork, straw and plaiting materials'),
  ('16.21', 4, '16.2', 'Manufacture of veneer sheets and wood-based panels'),
  ('16.22', 4, '16.2', 'Manufacture of assembled parquet floors'),
  ('16.23', 4, '16.2', 'Manufacture of other builders’ carpentry and joinery'),
  ('16.24', 4, '16.2', 'Manufacture of wooden containers'),
  ('16.25', 4, '16.2', 'Manufacture of doors and windows of wood'),
  ('16.26', 4, '16.2', 'Manufacture of solid fuels from vegetable biomass'),
  ('16.27', 4, '16.2', 'Finishing of wooden products'),
  ('16.28', 4, '16.2', 'Manufacture of other products of wood and articles of cork, straw and plaiting materials'),
  ('17', 2, 'C', 'Manufacture of paper and paper products'),
  ('17.1', 3, '17', 'Manufacture of pulp, paper and paperboard'),
  ('17.11', 4, '17.1', 'Manufacture of pulp'),
  ('17.12', 4, '17.1', 'Manufacture of paper and paperboard'),
  ('17.2', 3, '17', 'Manufacture of articles of paper and paperboard'),
  ('17.21', 4, '17.2', 'Manufacture of corrugated paper, paperboard and containers of paper and paperboard'),
  ('17.22', 4, '17.2', 'Manufacture of household and sanitary goods and of toilet requisites'),
  ('17.23', 4, '17.2', 'Manufacture of paper stationery'),
  ('17.24', 4, '17.2', 'Manufacture of wallpaper'),
  ('17.25', 4, '17.2', 'Manufacture of other articles of paper and paperboard'),
  ('18', 2, 'C', 'Printing and reproduction of recorded media'),
  ('18.1', 3, '18', 'Printing and service activities related to printing'),
  ('18.11', 4, '18.1', 'Printing of newspapers'),
  ('18.12', 4, '18.1', 'Other printing'),
  ('18.13', 4, '18.1', 'Pre-press and pre-media services'),
  ('18.14', 4, '18.1', 'Binding and related services'),
  ('18.2', 3, '18', 'Reproduction of recorded media'),
  ('18.20', 4, '18.2', 'Reproduction of recorded media'),
  ('19', 2, 'C', 'Manufacture of coke and refined petroleum products'),
  ('19.1', 3, '19', 'Manufacture of coke oven products'),
  ('19.10', 4, '19.1', 'Manufacture of coke oven products'),
  ('19.2', 3, '19', 'Manufacture of refined petroleum products and fossil fuel products'),
  ('19.20', 4, '19.2', 'Manufacture of refined petroleum products and fossil fuel products'),
  ('20', 2, 'C', 'Manufacture of chemicals and chemical products'),
  ('20.1', 3, '20', 'Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms'),
  ('20.11', 4, '20.1', 'Manufacture of industrial gases'),
  ('20.12', 4, '20.1', 'Manufacture of dyes and pigments'),
  ('20.13', 4, '20.1', 'Manufacture of other inorganic basic chemicals'),
  ('20.14', 4, '20.1', 'Manufacture of other organic basic chemicals'),
  ('20.15', 4, '20.1', 'Manufacture of fertilisers and nitrogen compounds'),
  ('20.16', 4, '20.1', 'Manufacture of plastics in primary forms'),
  ('20.17', 4, '20.1', 'Manufacture of synthetic rubber in primary forms'),
  ('20.2', 3, '20', 'Manufacture of pesticides, disinfectants and other agrochemical products'),
  ('20.20', 4, '20.2', 'Manufacture of pesticides, disinfectants and other agrochemical products'),
  ('20.3', 3, '20', 'Manufacture of paints, varnishes and similar coatings, printing ink and mastics'),
  ('20.30', 4, '20.3', 'Manufacture of paints, varnishes and similar coatings, printing ink and mastics'),
  ('20.4', 3, '20', 'Manufacture of washing, cleaning and polishing preparations'),
  ('20.41', 4, '20.4', 'Manufacture of soap and detergents, cleaning and polishing preparations'),
  ('20.42', 4, '20.4', 'Manufacture of perfume and toilet preparations'),
  ('20.5', 3, '20', 'Manufacture of other chemical products'),
  ('20.51', 4, '20.5', 'Manufacture of liquid biofuels'),
  ('20.59', 4, '20.5', 'Manufacture of other chemical products n.e.c.'),
  ('20.6', 3, '20', 'Manufacture of man-made fibres'),
  ('20.60', 4, '20.6', 'Manufacture of man-made fibres'),
  ('21', 2, 'C', 'Manufacture of basic pharmaceutical products and pharmaceutical preparations'),
  ('21.1', 3, '21', 'Manufacture of basic pharmaceutical products'),
  ('21.10', 4, '21.1', 'Manufacture of basic pharmaceutical products'),
  ('21.2', 3, '21', 'Manufacture of pharmaceutical preparations'),
  ('21.20', 4, '21.2', 'Manufacture of pharmaceutical preparations'),
  ('22', 2, 'C', 'Manufacture of rubber and plastic products'),
  ('22.1', 3, '22', 'Manufacture of rubber products'),
  ('22.11', 4, '22.1', 'Manufacture, retreading and rebuilding of rubber tyres and manufacture of tubes'),
  ('22.12', 4, '22.1', 'Manufacture of other rubber products'),
  ('22.2', 3, '22', 'Manufacture of plastic products'),
  ('22.21', 4, '22.2', 'Manufacture of plastic plates, sheets, tubes and profiles'),
  ('22.22', 4, '22.2', 'Manufacture of plastic packing goods'),
  ('22.23', 4, '22.2', 'Manufacture of doors and windows of plastic'),
  ('22.24', 4, '22.2', 'Manufacture of builders’ ware of plastic'),
  ('22.25', 4, '22.2', 'Processing and finishing of plastic products'),
  ('22.26', 4, '22.2', 'Manufacture of other plastic products'),
  ('23', 2, 'C', 'Manufacture of other non-metallic mineral products'),
  ('23.1', 3, '23', 'Manufacture of glass and glass products'),
  ('23.11', 4, '23.1', 'Manufacture of flat glass'),
  ('23.12', 4, '23.1', 'Shaping and processing of flat glass'),
  ('23.13', 4, '23.1', 'Manufacture of hollow glass'),
  ('23.14', 4, '23.1', 'Manufacture of glass fibres'),
  ('23.15', 4, '23.1', 'Manufacture and processing of other glass, including technical glassware'),
  ('23.2', 3, '23', 'Manufacture of refractory products'),
  ('23.20', 4, '23.2', 'Manufacture of refractory products'),
  ('23.3', 3, '23', 'Manufacture of clay building materials'),
  ('23.31', 4, '23.3', 'Manufacture of ceramic tiles and flags'),
  ('23.32', 4, '23.3', 'Manufacture of bricks, tiles and construction products, in baked clay'),
  ('23.4', 3, '23', 'Manufacture of other porcelain and ceramic products'),
  ('23.41', 4, '23.4', 'Manufacture of ceramic household and ornamental articles'),
  ('23.42', 4, '23.4', 'Manufacture of ceramic sanitary fixtures'),
  ('23.43', 4, '23.4', 'Manufacture of ceramic insulators and insulating fittings'),
  ('23.44', 4, '23.4', 'Manufacture of other technical ceramic products'),
  ('23.45', 4, '23.4', 'Manufacture of other ceramic products'),
  ('23.5', 3, '23', 'Manufacture of cement, lime and plaster'),
  ('23.51', 4, '23.5', 'Manufacture of cement'),
  ('23.52', 4, '23.5', 'Manufacture of lime and plaster'),
  ('23.6', 3, '23', 'Manufacture of articles of concrete, cement and plaster'),
  ('23.61', 4, '23.6', 'Manufacture of concrete products for construction purposes'),
  ('23.62', 4, '23.6', 'Manufacture of plaster products for construction purposes'),
  ('23.63', 4, '23.6', 'Manufacture of ready-mixed concrete'),
  ('23.64', 4, '23.6', 'Manufacture of mortars'),
  ('23.65', 4, '23.6', 'Manufacture of fibre cement'),
  ('23.66', 4, '23.6', 'Manufacture of other articles of concrete, cement and plaster'),
  ('23.7', 3, '23', 'Cutting, shaping and finishing of stone'),
  ('23.70', 4, '23.7', 'Cutting, shaping and finishing of stone'),
  ('23.9', 3, '23', 'Manufacture of abrasive products and non-metallic mineral products n.e.c.'),
  ('23.91', 4, '23.9', 'Manufacture of abrasive products'),
  ('23.99', 4, '23.9', 'Manufacture of other non-metallic mineral products n.e.c.'),
  ('24', 2, 'C', 'Manufacture of basic metals'),
  ('24.1', 3, '24', 'Manufacture of basic iron and steel and of ferro-alloys'),
  ('24.10', 4, '24.1', 'Manufacture of basic iron and steel and of ferro-alloys'),
  ('24.2', 3, '24', 'Manufacture of tubes, pipes, hollow profiles and related fittings, of steel'),
  ('24.20', 4, '24.2', 'Manufacture of tubes, pipes, hollow profiles and related fittings, of steel'),
  ('24.3', 3, '24', 'Manufacture of other products of first processing of steel'),
  ('24.31', 4, '24.3', 'Cold drawing of bars'),
  ('24.32', 4, '24.3', 'Cold rolling of narrow strip'),
  ('24.33', 4, '24.3', 'Cold forming or folding'),
  ('24.34', 4, '24.3', 'Cold drawing of wire'),
  ('24.4', 3, '24', 'Manufacture of basic precious and other non-ferrous metals'),
  ('24.41', 4, '24.4', 'Precious metals production'),
  ('24.42', 4, '24.4', 'Aluminium production'),
  ('24.43', 4, '24.4', 'Lead, zinc and tin production'),
  ('24.44', 4, '24.4', 'Copper production'),
  ('24.45', 4, '24.4', 'Other non-ferrous metal production'),
  ('24.46', 4, '24.4', 'Processing of nuclear fuel'),
  ('24.5', 3, '24', 'Casting of metals'),
  ('24.51', 4, '24.5', 'Casting of iron'),
  ('24.52', 4, '24.5', 'Casting of steel'),
  ('24.53', 4, '24.5', 'Casting of light metals'),
  ('24.54', 4, '24.5', 'Casting of other non-ferrous metals'),
  ('25', 2, 'C', 'Manufacture of fabricated metal products, except machinery and equipment'),
  ('25.1', 3, '25', 'Manufacture of structural metal products'),
  ('25.11', 4, '25.1', 'Manufacture of metal structures and parts of structures'),
  ('25.12', 4, '25.1', 'Manufacture of doors and windows of metal'),
  ('25.2', 3, '25', 'Manufacture of tanks, reservoirs and containers of metal'),
  ('25.21', 4, '25.2', 'Manufacture of central heating radiators, steam generators and boilers'),
  ('25.22', 4, '25.2', 'Manufacture of other tanks, reservoirs and containers of metal'),
  ('25.3', 3, '25', 'Manufacture of weapons and ammunition'),
  ('25.30', 4, '25.3', 'Manufacture of weapons and ammunition'),
  ('25.4', 3, '25', 'Forging and shaping metal and powder metallurgy'),
  ('25.40', 4, '25.4', 'Forging and shaping metal and powder metallurgy'),
  ('25.5', 3, '25', 'Treatment and coating of metals; machining'),
  ('25.51', 4, '25.5', 'Coating of metals'),
  ('25.52', 4, '25.5', 'Heat treatment of metals'),
  ('25.53', 4, '25.5', 'Machining of metals'),
  ('25.6', 3, '25', 'Manufacture of cutlery, tools and general hardware'),
  ('25.61', 4, '25.6', 'Manufacture of cutlery'),
  ('25.62', 4, '25.6', 'Manufacture of locks and hinges'),
  ('25.63', 4, '25.6', 'Manufacture of tools'),
  ('25.9', 3, '25', 'Manufacture of other fabricated metal products'),
  ('25.91', 4, '25.9', 'Manufacture of steel drums and similar containers'),
  ('25.92', 4, '25.9', 'Manufacture of light metal packaging'),
  ('25.93', 4, '25.9', 'Manufacture of wire products, chain and springs'),
  ('25.94', 4, '25.9', 'Manufacture of fasteners and screw machine products'),
  ('25.99', 4, '25.9', 'Manufacture of other fabricated metal products n.e.c.'),
  ('26', 2, 'C', 'Manufacture of computer, electronic and optical products'),
  ('26.1', 3, '26', 'Manufacture of electronic components and boards'),
  ('26.11', 4, '26.1', 'Manufacture of electronic components'),
  ('26.12', 4, '26.1', 'Manufacture of loaded electronic boards'),
  ('26.2', 3, '26', 'Manufacture of computers and peripheral equipment'),
  ('26.20', 4, '26.2', 'Manufacture of computers and peripheral equipment'),
  ('26.3', 3, '26', 'Manufacture of communication equipment'),
  ('26.30', 4, '26.3', 'Manufacture of communication equipment'),
  ('26.4', 3, '26', 'Manufacture of consumer electronics'),
  ('26.40', 4, '26.4', 'Manufacture of consumer electronics'),
  ('26.5', 3, '26', 'Manufacture of measuring testing instruments, clocks and watches'),
  ('26.51', 4, '26.5', 'Manufacture of instruments and appliances for measuring, testing and navigation'),
  ('26.52', 4, '26.5', 'Manufacture of watches and clocks'),
  ('26.6', 3, '26', 'Manufacture of irradiation, electromedical and electrotherapeutic equipment'),
  ('26.60', 4, '26.6', 'Manufacture of irradiation, electromedical and electrotherapeutic equipment'),
  ('26.7', 3, '26', 'Manufacture of optical instruments, magnetic and optical media and photographic equipment'),
  ('26.70', 4, '26.7', 'Manufacture of optical instruments, magnetic and optical media and photographic equipment'),
  ('27', 2, 'C', 'Manufacture of electrical equipment'),
  ('27.1', 3, '27', 'Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus'),
  ('27.11', 4, '27.1', 'Manufacture of electric motors, generators and transformers'),
  ('27.12', 4, '27.1', 'Manufacture of electricity distribution and control apparatus'),
  ('27.2', 3, '27', 'Manufacture of batteries and accumulators'),
  ('27.20', 4, '27.2', 'Manufacture of batteries and accumulators'),
  ('27.3', 3, '27', 'Manufacture of wiring and wiring devices'),
  ('27.31', 4, '27.3', 'Manufacture of fibre optic cables'),
  ('27.32', 4, '27.3', 'Manufacture of other electronic and electric wires and cables'),
  ('27.33', 4, '27.3', 'Manufacture of wiring devices'),
  ('27.4', 3, '27', 'Manufacture of lighting equipment'),
  ('27.40', 4, '27.4', 'Manufacture of lighting equipment'),
  ('27.5', 3, '27', 'Manufacture of domestic appliances'),
  ('27.51', 4, '27.5', 'Manufacture of electric domestic appliances'),
  ('27.52', 4, '27.5', 'Manufacture of non-electric domestic appliances'),
  ('27.9', 3, '27', 'Manufacture of other electrical equipment'),
  ('27.90', 4, '27.9', 'Manufacture of other electrical equipment'),
  ('28', 2, 'C', 'Manufacture of machinery and equipment n.e.c.'),
  ('28.1', 3, '28', 'Manufacture of general-purpose machinery'),
  ('28.11', 4, '28.1', 'Manufacture of engines and turbines, except aircraft, vehicle and cycle engines'),
  ('28.12', 4, '28.1', 'Manufacture of fluid power equipment'),
  ('28.13', 4, '28.1', 'Manufacture of other pumps and compressors'),
  ('28.14', 4, '28.1', 'Manufacture of other taps and valves'),
  ('28.15', 4, '28.1', 'Manufacture of bearings, gears, gearing and driving elements'),
  ('28.2', 3, '28', 'Manufacture of other general-purpose machinery'),
  ('28.21', 4, '28.2', 'Manufacture of ovens, furnaces and permanent household heating equipment'),
  ('28.22', 4, '28.2', 'Manufacture of lifting and handling equipment'),
  ('28.23', 4, '28.2', 'Manufacture of office machinery and equipment, except computers and peripheral equipment'),
  ('28.24', 4, '28.2', 'Manufacture of power-driven hand tools'),
  ('28.25', 4, '28.2', 'Manufacture of non-domestic air conditioning equipment'),
  ('28.29', 4, '28.2', 'Manufacture of other general-purpose machinery n.e.c.'),
  ('28.3', 3, '28', 'Manufacture of agricultural and forestry machinery'),
  ('28.30', 4, '28.3', 'Manufacture of agricultural and forestry machinery'),
  ('28.4', 3, '28', 'Manufacture of metal forming machinery and machine tools'),
  ('28.41', 4, '28.4', 'Manufacture of metal forming machinery and machine tools for metal work'),
  ('28.42', 4, '28.4', 'Manufacture of other machine tools'),
  ('28.9', 3, '28', 'Manufacture of other special-purpose machinery'),
  ('28.91', 4, '28.9', 'Manufacture of machinery for metallurgy'),
  ('28.92', 4, '28.9', 'Manufacture of machinery for mining, quarrying and construction'),
  ('28.93', 4, '28.9', 'Manufacture of machinery for food, beverage and tobacco processing'),
  ('28.94', 4, '28.9', 'Manufacture of machinery for textile, apparel and leather production'),
  ('28.95', 4, '28.9', 'Manufacture of machinery for paper and paperboard production'),
  ('28.96', 4, '28.9', 'Manufacture of plastics and rubber machinery'),
  ('28.97', 4, '28.9', 'Manufacture of additive manufacturing machinery'),
  ('28.99', 4, '28.9', 'Manufacture of other special-purpose machinery n.e.c.'),
  ('29', 2, 'C', 'Manufacture of motor vehicles, trailers and semi-trailers'),
  ('29.1', 3, '29', 'Manufacture of motor vehicles'),
  ('29.10', 4, '29.1', 'Manufacture of motor vehicles'),
  ('29.2', 3, '29', 'Manufacture of bodies and coachwork for motor vehicles; manufacture of trailers and semi-trailers'),
  ('29.20', 4, '29.2', 'Manufacture of bodies and coachwork for motor vehicles; manufacture of trailers and semi-trailers'),
  ('29.3', 3, '29', 'Manufacture of motor vehicle parts and accessories'),
  ('29.31', 4, '29.3', 'Manufacture of electrical and electronic equipment for motor vehicles'),
  ('29.32', 4, '29.3', 'Manufacture of other parts and accessories for motor vehicles'),
  ('30', 2, 'C', 'Manufacture of other transport equipment'),
  ('30.1', 3, '30', 'Building of ships and boats'),
  ('30.11', 4, '30.1', 'Building of civilian ships and floating structures'),
  ('30.12', 4, '30.1', 'Building of pleasure and sporting boats'),
  ('30.13', 4, '30.1', 'Building of military ships and vessels'),
  ('30.2', 3, '30', 'Manufacture of railway locomotives and rolling stock'),
  ('30.20', 4, '30.2', 'Manufacture of railway locomotives and rolling stock'),
  ('30.3', 3, '30', 'Manufacture of air and spacecraft and related machinery'),
  ('30.31', 4, '30.3', 'Manufacture of civilian air and spacecraft and related machinery'),
  ('30.32', 4, '30.3', 'Manufacture of military air and spacecraft and related machinery'),
  ('30.4', 3, '30', 'Manufacture of military fighting vehicles'),
  ('30.40', 4, '30.4', 'Manufacture of military fighting vehicles'),
  ('30.9', 3, '30', 'Manufacture of transport equipment n.e.c.'),
  ('30.91', 4, '30.9', 'Manufacture of motorcycles'),
  ('30.92', 4, '30.9', 'Manufacture of bicycles and invalid carriages'),
  ('30.99', 4, '30.9', 'Manufacture of other transport equipment n.e.c.'),
  ('31', 2, 'C', 'Manufacture of furniture'),
  ('31.0', 3, '31', 'Manufacture of furniture'),
  ('31.00', 4, '31.0', 'Manufacture of furniture'),
  ('32', 2, 'C', 'Other manufacturing'),
  ('32.1', 3, '32', 'Manufacture of jewellery, bijouterie and related articles'),
  ('32.11', 4, '32.1', 'Striking of coins'),
  ('32.12', 4, '32.1', 'Manufacture of jewellery and related articles'),
  ('32.13', 4, '32.1', 'Manufacture of imitation jewellery and related articles'),
  ('32.2', 3, '32', 'Manufacture of musical instruments'),
  ('32.20', 4, '32.2', 'Manufacture of musical instruments'),
  ('32.3', 3, '32', 'Manufacture of sports goods'),
  ('32.30', 4, '32.3', 'Manufacture of sports goods'),
  ('32.4', 3, '32', 'Manufacture of games and toys'),
  ('32.40', 4, '32.4', 'Manufacture of games and toys'),
  ('32.5', 3, '32', 'Manufacture of medical and dental instruments and supplies'),
  ('32.50', 4, '32.5', 'Manufacture of medical and dental instruments and supplies'),
  ('32.9', 3, '32', 'Manufacturing n.e.c.'),
  ('32.91', 4, '32.9', 'Manufacture of brooms and brushes'),
  ('32.99', 4, '32.9', 'Other manufacturing n.e.c.'),
  ('33', 2, 'C', 'Repair, maintenance and installation of machinery and equipment'),
  ('33.1', 3, '33', 'Repair and maintenance of fabricated metal products, machinery and equipment'),
  ('33.11', 4, '33.1', 'Repair and maintenance of fabricated metal products'),
  ('33.12', 4, '33.1', 'Repair and maintenance of machinery'),
  ('33.13', 4, '33.1', 'Repair and maintenance of electronic and optical equipment'),
  ('33.14', 4, '33.1', 'Repair and maintenance of electrical equipment'),
  ('33.15', 4, '33.1', 'Repair and maintenance of civilian ships and boats'),
  ('33.16', 4, '33.1', 'Repair and maintenance of civilian air and spacecraft'),
  ('33.17', 4, '33.1', 'Repair and maintenance of other civilian transport equipment'),
  ('33.18', 4, '33.1', 'Repair and maintenance of military fighting vehicles, ships, boats, air and spacecraft'),
  ('33.19', 4, '33.1', 'Repair and maintenance of other equipment'),
  ('33.2', 3, '33', 'Installation of industrial machinery and equipment'),
  ('33.20', 4, '33.2', 'Installation of industrial machinery and equipment'),
  ('35', 2, 'D', 'Electricity, gas, steam and air conditioning supply'),
  ('35.1', 3, '35', 'Electric power generation, transmission and distribution'),
  ('35.11', 4, '35.1', 'Production of electricity from non-renewable sources'),
  ('35.12', 4, '35.1', 'Production of electricity from renewable sources'),
  ('35.13', 4, '35.1', 'Transmission of electricity'),
  ('35.14', 4, '35.1', 'Distribution of electricity'),
  ('35.15', 4, '35.1', 'Trade of electricity'),
  ('35.16', 4, '35.1', 'Storage of electricity'),
  ('35.2', 3, '35', 'Manufacture of gas, and distribution of gaseous fuels through mains'),
  ('35.21', 4, '35.2', 'Manufacture of gas'),
  ('35.22', 4, '35.2', 'Distribution of gaseous fuels through mains'),
  ('35.23', 4, '35.2', 'Trade of gas through mains'),
  ('35.24', 4, '35.2', 'Storage of gas as part of network supply services'),
  ('35.3', 3, '35', 'Steam and air conditioning supply'),
  ('35.30', 4, '35.3', 'Steam and air conditioning supply'),
  ('35.4', 3, '35', 'Activities of brokers and agents for electric power and natural gas'),
  ('35.40', 4, '35.4', 'Activities of brokers and agents for electric power and natural gas'),
  ('36', 2, 'E', 'Water collection, treatment and supply'),
  ('36.0', 3, '36', 'Water collection, treatment and supply'),
  ('36.00', 4, '36.0', 'Water collection, treatment and supply'),
  ('37', 2, 'E', 'Sewerage'),
  ('37.0', 3, '37', 'Sewerage'),
  ('37.00', 4, '37.0', 'Sewerage'),
  ('38', 2, 'E', 'Waste collection, recovery and disposal activities'),
  ('38.1', 3, '38', 'Waste collection'),
  ('38.11', 4, '38.1', 'Collection of non-hazardous waste'),
  ('38.12', 4, '38.1', 'Collection of hazardous waste'),
  ('38.2', 3, '38', 'Waste recovery'),
  ('38.21', 4, '38.2', 'Materials recovery'),
  ('38.22', 4, '38.2', 'Energy recovery'),
  ('38.23', 4, '38.2', 'Other waste recovery'),
  ('38.3', 3, '38', 'Waste disposal without recovery'),
  ('38.31', 4, '38.3', 'Incineration without energy recovery'),
  ('38.32', 4, '38.3', 'Landfilling or permanent storage'),
  ('38.33', 4, '38.3', 'Other waste disposal'),
  ('39', 2, 'E', 'Remediation activities and other waste management service activities'),
  ('39.0', 3, '39', 'Remediation activities and other waste management service activities'),
  ('39.00', 4, '39.0', 'Remediation activities and other waste management service activities'),
  ('41', 2, 'F', 'Construction of residential and non-residential buildings'),
  ('41.0', 3, '41', 'Construction of residential and non-residential buildings'),
  ('41.00', 4, '41.0', 'Construction of residential and non-residential buildings'),
  ('42', 2, 'F', 'Civil engineering'),
  ('42.1', 3, '42', 'Construction of roads and railways'),
  ('42.11', 4, '42.1', 'Construction of roads and motorways'),
  ('42.12', 4, '42.1', 'Construction of railways and underground railways'),
  ('42.13', 4, '42.1', 'Construction of bridges and tunnels'),
  ('42.2', 3, '42', 'Construction of utility projects'),
  ('42.21', 4, '42.2', 'Construction of utility projects for fluids'),
  ('42.22', 4, '42.2', 'Construction of utility projects for electricity and telecommunications'),
  ('42.9', 3, '42', 'Construction of other civil engineering projects'),
  ('42.91', 4, '42.9', 'Construction of water projects'),
  ('42.99', 4, '42.9', 'Construction of other civil engineering projects n.e.c.'),
  ('43', 2, 'F', 'Specialised construction activities'),
  ('43.1', 3, '43', 'Demolition and site preparation'),
  ('43.11', 4, '43.1', 'Demolition'),
  ('43.12', 4, '43.1', 'Site preparation'),
  ('43.13', 4, '43.1', 'Test drilling and boring'),
  ('43.2', 3, '43', 'Electrical, plumbing and other construction installation activities'),
  ('43.21', 4, '43.2', 'Electrical installation'),
  ('43.22', 4, '43.2', 'Plumbing, heat and air-conditioning installation'),
  ('43.23', 4, '43.2', 'Installation of insulation'),
  ('43.24', 4, '43.2', 'Other construction installation'),
  ('43.3', 3, '43', 'Building completion and finishing'),
  ('43.31', 4, '43.3', 'Plastering'),
  ('43.32', 4, '43.3', 'Joinery installation'),
  ('43.33', 4, '43.3', 'Floor and wall covering'),
  ('43.34', 4, '43.3', 'Painting and glazing'),
  ('43.35', 4, '43.3', 'Other building completion and finishing'),
  ('43.4', 3, '43', 'Specialised construction activities in construction of buildings'),
  ('43.41', 4, '43.4', 'Roofing activities'),
  ('43.42', 4, '43.4', 'Other specialised construction activities in construction of buildings'),
  ('43.5', 3, '43', 'Specialised construction activities in civil engineering'),
  ('43.50', 4, '43.5', 'Specialised construction activities in civil engineering'),
  ('43.6', 3, '43', 'Intermediation service activities for specialised construction services'),
  ('43.60', 4, '43.6', 'Intermediation service activities for specialised construction services'),
  ('43.9', 3, '43', 'Other specialised construction activities'),
  ('43.91', 4, '43.9', 'Masonry and bricklaying activities'),
  ('43.99', 4, '43.9', 'Other specialised construction activities n.e.c.'),
  ('46', 2, 'G', 'Wholesale trade'),
  ('46.1', 3, '46', 'Wholesale on a fee or contract basis'),
  ('46.11', 4, '46.1', 'Activities of agents involved in the wholesale of agricultural raw materials, live animals, textile raw materials and semi-finished goods'),
  ('46.12', 4, '46.1', 'Activities of agents involved in the wholesale of fuels, ores, metals and industrial chemicals'),
  ('46.13', 4, '46.1', 'Activities of agents involved in the wholesale of timber and building materials'),
  ('46.14', 4, '46.1', 'Activities of agents involved in the wholesale of machinery, industrial equipment, ships and aircraft'),
  ('46.15', 4, '46.1', 'Activities of agents involved in the wholesale of furniture, household goods, hardware and ironmongery'),
  ('46.16', 4, '46.1', 'Activities of agents involved in the wholesale of textiles, clothing, fur, footwear and leather goods'),
  ('46.17', 4, '46.1', 'Activities of agents involved in the wholesale of food, beverages and tobacco'),
  ('46.18', 4, '46.1', 'Activities of agents involved in the wholesale of other particular products'),
  ('46.19', 4, '46.1', 'Activities of agents involved in non-specialised wholesale'),
  ('46.2', 3, '46', 'Wholesale of agricultural raw materials and live animals'),
  ('46.21', 4, '46.2', 'Wholesale of grain, unmanufactured tobacco, seeds and animal feeds'),
  ('46.22', 4, '46.2', 'Wholesale of flowers and plants'),
  ('46.23', 4, '46.2', 'Wholesale of live animals'),
  ('46.24', 4, '46.2', 'Wholesale of hides, skins and leather'),
  ('46.3', 3, '46', 'Wholesale of food, beverages and tobacco'),
  ('46.31', 4, '46.3', 'Wholesale of fruit and vegetables'),
  ('46.32', 4, '46.3', 'Wholesale of meat, meat products, fish and fish products'),
  ('46.33', 4, '46.3', 'Wholesale of dairy products, eggs and edible oils and fats'),
  ('46.34', 4, '46.3', 'Wholesale of beverages'),
  ('46.35', 4, '46.3', 'Wholesale of tobacco products'),
  ('46.36', 4, '46.3', 'Wholesale of sugar, chocolate and sugar confectionery'),
  ('46.37', 4, '46.3', 'Wholesale of coffee, tea, cocoa and spices'),
  ('46.38', 4, '46.3', 'Wholesale of other food'),
  ('46.39', 4, '46.3', 'Non-specialised wholesale of food, beverages and tobacco'),
  ('46.4', 3, '46', 'Wholesale of household goods'),
  ('46.41', 4, '46.4', 'Wholesale of textiles'),
  ('46.42', 4, '46.4', 'Wholesale of clothing and footwear'),
  ('46.43', 4, '46.4', 'Wholesale of electrical household appliances'),
  ('46.44', 4, '46.4', 'Wholesale of china and glassware and cleaning materials'),
  ('46.45', 4, '46.4', 'Wholesale of perfume and cosmetics'),
  ('46.46', 4, '46.4', 'Wholesale of pharmaceutical and medical goods'),
  ('46.47', 4, '46.4', 'Wholesale of household, office and shop furniture, carpets and lighting equipment'),
  ('46.48', 4, '46.4', 'Wholesale of watches and jewellery'),
  ('46.49', 4, '46.4', 'Wholesale of other household goods'),
  ('46.5', 3, '46', 'Wholesale of information and communication equipment'),
  ('46.50', 4, '46.5', 'Wholesale of information and communication equipment'),
  ('46.6', 3, '46', 'Wholesale of other machinery, equipment and supplies'),
  ('46.61', 4, '46.6', 'Wholesale of agricultural machinery, equipment and supplies'),
  ('46.62', 4, '46.6', 'Wholesale of machine tools'),
  ('46.63', 4, '46.6', 'Wholesale of mining, construction and civil engineering machinery'),
  ('46.64', 4, '46.6', 'Wholesale of other machinery and equipment'),
  ('46.7', 3, '46', 'Wholesale of motor vehicles, motorcycles and related parts and accessories'),
  ('46.71', 4, '46.7', 'Wholesale of motor vehicles'),
  ('46.72', 4, '46.7', 'Wholesale of motor vehicle parts and accessories'),
  ('46.73', 4, '46.7', 'Wholesale of motorcycles, motorcycle parts and accessories'),
  ('46.8', 3, '46', 'Other specialised wholesale'),
  ('46.81', 4, '46.8', 'Wholesale of solid, liquid and gaseous fuels and related products'),
  ('46.82', 4, '46.8', 'Wholesale of metals and metal ores'),
  ('46.83', 4, '46.8', 'Wholesale of wood, construction materials and sanitary equipment'),
  ('46.84', 4, '46.8', 'Wholesale of hardware, plumbing and heating equipment and supplies'),
  ('46.85', 4, '46.8', 'Wholesale of chemical products'),
  ('46.86', 4, '46.8', 'Wholesale of other intermediate products'),
  ('46.87', 4, '46.8', 'Wholesale of waste and scrap'),
  ('46.89', 4, '46.8', 'Other specialised wholesale n.e.c.'),
  ('46.9', 3, '46', 'Non-specialised wholesale trade'),
  ('46.90', 4, '46.9', 'Non-specialised wholesale trade'),
  ('47', 2, 'G', 'Retail trade'),
  ('47.1', 3, '47', 'Non-specialised retail sale'),
  ('47.11', 4, '47.1', 'Non-specialised retail sale of predominately food, beverages or tobacco'),
  ('47.12', 4, '47.1', 'Other non-specialised retail sale'),
  ('47.2', 3, '47', 'Retail sale of food, beverages and tobacco'),
  ('47.21', 4, '47.2', 'Retail sale of fruit and vegetables'),
  ('47.22', 4, '47.2', 'Retail sale of meat and meat products'),
  ('47.23', 4, '47.2', 'Retail sale of fish, crustaceans and molluscs'),
  ('47.24', 4, '47.2', 'Retail sale of bread, cake and confectionery'),
  ('47.25', 4, '47.2', 'Retail sale of beverages'),
  ('47.26', 4, '47.2', 'Retail sale of tobacco products'),
  ('47.27', 4, '47.2', 'Retail sale of other food'),
  ('47.3', 3, '47', 'Retail sale of automotive fuel'),
  ('47.30', 4, '47.3', 'Retail sale of automotive fuel'),
  ('47.4', 3, '47', 'Retail sale of information and communication equipment'),
  ('47.40', 4, '47.4', 'Retail sale of information and communication equipment'),
  ('47.5', 3, '47', 'Retail sale of other household equipment'),
  ('47.51', 4, '47.5', 'Retail sale of textiles'),
  ('47.52', 4, '47.5', 'Retail sale of hardware, building materials, paints and glass'),
  ('47.53', 4, '47.5', 'Retail sale of carpets, rugs, wall and floor coverings'),
  ('47.54', 4, '47.5', 'Retail sale of electrical household appliances'),
  ('47.55', 4, '47.5', 'Retail sale of furniture, lighting equipment, tableware and other household goods'),
  ('47.6', 3, '47', 'Retail sale of cultural and recreation goods'),
  ('47.61', 4, '47.6', 'Retail sale of books'),
  ('47.62', 4, '47.6', 'Retail sale of newspapers, and other periodical publications and stationery'),
  ('47.63', 4, '47.6', 'Retail sale of sporting equipment'),
  ('47.64', 4, '47.6', 'Retail sale of games and toys'),
  ('47.69', 4, '47.6', 'Retail sale of cultural and recreational goods n.e.c.'),
  ('47.7', 3, '47', 'Retail sale of other goods, except motor vehicles and motorcycles'),
  ('47.71', 4, '47.7', 'Retail sale of clothing'),
  ('47.72', 4, '47.7', 'Retail sale of footwear and leather goods'),
  ('47.73', 4, '47.7', 'Retail sale of pharmaceutical products'),
  ('47.74', 4, '47.7', 'Retail sale of medical and orthopaedic goods'),
  ('47.75', 4, '47.7', 'Retail sale of cosmetic and toilet articles'),
  ('47.76', 4, '47.7', 'Retail sale of flowers, plants, fertilisers, pets and pet food'),
  ('47.77', 4, '47.7', 'Retail sale of watches and jewellery'),
  ('47.78', 4, '47.7', 'Retail sale of other new goods'),
  ('47.79', 4, '47.7', 'Retail sale of second-hand goods'),
  ('47.8', 3, '47', 'Retail sale of motor vehicles, motorcycles and related parts and accessories'),
  ('47.81', 4, '47.8', 'Retail sale of motor vehicles'),
  ('47.82', 4, '47.8', 'Retail sale of motor vehicle parts and accessories'),
  ('47.83', 4, '47.8', 'Retail sale of motorcycles, motorcycle parts and accessories'),
  ('47.9', 3, '47', 'Intermediation service activities for retail sale'),
  ('47.91', 4, '47.9', 'Intermediation service activities for non-specialised retail sale'),
  ('47.92', 4, '47.9', 'Intermediation service activities for specialised retail sale'),
  ('49', 2, 'H', 'Land transport and transport via pipelines'),
  ('49.1', 3, '49', 'Passenger rail transport'),
  ('49.11', 4, '49.1', 'Passenger heavy rail transport'),
  ('49.12', 4, '49.1', 'Other passenger rail transport'),
  ('49.2', 3, '49', 'Freight rail transport'),
  ('49.20', 4, '49.2', 'Freight rail transport'),
  ('49.3', 3, '49', 'Other passenger land transport'),
  ('49.31', 4, '49.3', 'Scheduled passenger transport by road'),
  ('49.32', 4, '49.3', 'Non-scheduled passenger transport by road'),
  ('49.33', 4, '49.3', 'On-demand passenger transport service activities by vehicle with driver'),
  ('49.34', 4, '49.3', 'Passenger transport by cableways and ski lifts'),
  ('49.39', 4, '49.3', 'Other passenger land transport n.e.c.'),
  ('49.4', 3, '49', 'Freight transport by road and removal services'),
  ('49.41', 4, '49.4', 'Freight transport by road'),
  ('49.42', 4, '49.4', 'Removal services'),
  ('49.5', 3, '49', 'Transport via pipeline'),
  ('49.50', 4, '49.5', 'Transport via pipeline'),
  ('50', 2, 'H', 'Water transport'),
  ('50.1', 3, '50', 'Sea and coastal passenger water transport'),
  ('50.10', 4, '50.1', 'Sea and coastal passenger water transport'),
  ('50.2', 3, '50', 'Sea and coastal freight water transport'),
  ('50.20', 4, '50.2', 'Sea and coastal freight water transport'),
  ('50.3', 3, '50', 'Inland passenger water transport'),
  ('50.30', 4, '50.3', 'Inland passenger water transport'),
  ('50.4', 3, '50', 'Inland freight water transport'),
  ('50.40', 4, '50.4', 'Inland freight water transport'),
  ('51', 2, 'H', 'Air transport'),
  ('51.1', 3, '51', 'Passenger air transport'),
  ('51.10', 4, '51.1', 'Passenger air transport'),
  ('51.2', 3, '51', 'Freight air transport and space transport'),
  ('51.21', 4, '51.2', 'Freight air transport'),
  ('51.22', 4, '51.2', 'Space transport'),
  ('52', 2, 'H', 'Warehousing, storage and support activities for transportation'),
  ('52.1', 3, '52', 'Warehousing and storage'),
  ('52.10', 4, '52.1', 'Warehousing and storage'),
  ('52.2', 3, '52', 'Support activities for transportation'),
  ('52.21', 4, '52.2', 'Service activities incidental to land transportation'),
  ('52.22', 4, '52.2', 'Service activities incidental to water transportation'),
  ('52.23', 4, '52.2', 'Service activities incidental to air transportation'),
  ('52.24', 4, '52.2', 'Cargo handling'),
  ('52.25', 4, '52.2', 'Logistics service activities'),
  ('52.26', 4, '52.2', 'Other support activities for transportation'),
  ('52.3', 3, '52', 'Intermediation service activities for transportation'),
  ('52.31', 4, '52.3', 'Intermediation service activities for freight transportation'),
  ('52.32', 4, '52.3', 'Intermediation service activities for passenger transportation'),
  ('53', 2, 'H', 'Postal and courier activities'),
  ('53.1', 3, '53', 'Postal activities under universal service obligation'),
  ('53.10', 4, '53.1', 'Postal activities under universal service obligation'),
  ('53.2', 3, '53', 'Other postal and courier activities'),
  ('53.20', 4, '53.2', 'Other postal and courier activities'),
  ('53.3', 3, '53', 'Intermediation service activities for postal and courier activities'),
  ('53.30', 4, '53.3', 'Intermediation service activities for postal and courier activities'),
  ('55', 2, 'I', 'Accommodation'),
  ('55.1', 3, '55', 'Hotels and similar accommodation'),
  ('55.10', 4, '55.1', 'Hotels and similar accommodation'),
  ('55.2', 3, '55', 'Holiday and other short-stay accommodation'),
  ('55.20', 4, '55.2', 'Holiday and other short-stay accommodation'),
  ('55.3', 3, '55', 'Camping grounds and recreational vehicle parks'),
  ('55.30', 4, '55.3', 'Camping grounds and recreational vehicle parks'),
  ('55.4', 3, '55', 'Intermediation service activities for accommodation'),
  ('55.40', 4, '55.4', 'Intermediation service activities for accommodation'),
  ('55.9', 3, '55', 'Other accommodation'),
  ('55.90', 4, '55.9', 'Other accommodation'),
  ('56', 2, 'I', 'Food and beverage service activities'),
  ('56.1', 3, '56', 'Restaurants and mobile food service activities'),
  ('56.11', 4, '56.1', 'Restaurant activities'),
  ('56.12', 4, '56.1', 'Mobile food service activities'),
  ('56.2', 3, '56', 'Event catering, contract catering service activities and other food service activities'),
  ('56.21', 4, '56.2', 'Event catering activities'),
  ('56.22', 4, '56.2', 'Contract catering service activities and other food service activities'),
  ('56.3', 3, '56', 'Beverage serving activities'),
  ('56.30', 4, '56.3', 'Beverage serving activities'),
  ('56.4', 3, '56', 'Intermediation service activities for food and beverage services activities'),
  ('56.40', 4, '56.4', 'Intermediation service activities for food and beverage services activities'),
  ('58', 2, 'J', 'Publishing activities'),
  ('58.1', 3, '58', 'Publishing of books, newspapers and other publishing activities, except software publishing'),
  ('58.11', 4, '58.1', 'Publishing of books'),
  ('58.12', 4, '58.1', 'Publishing of newspapers'),
  ('58.13', 4, '58.1', 'Publishing of journals and periodicals'),
  ('58.19', 4, '58.1', 'Other publishing activities, except software publishing'),
  ('58.2', 3, '58', 'Software publishing'),
  ('58.21', 4, '58.2', 'Publishing of video games'),
  ('58.29', 4, '58.2', 'Other software publishing'),
  ('59', 2, 'J', 'Motion picture, video and television programme production, sound recording and music publishing activities'),
  ('59.1', 3, '59', 'Motion picture, video and television programme activities'),
  ('59.11', 4, '59.1', 'Motion picture, video and television programme production activities'),
  ('59.12', 4, '59.1', 'Motion picture, video and television programme post-production activities'),
  ('59.13', 4, '59.1', 'Motion picture and video distribution activities'),
  ('59.14', 4, '59.1', 'Motion picture projection activities'),
  ('59.2', 3, '59', 'Sound recording and music publishing activities'),
  ('59.20', 4, '59.2', 'Sound recording and music publishing activities'),
  ('60', 2, 'J', 'Programming, broadcasting, news agency and other content distribution activities'),
  ('60.1', 3, '60', 'Radio broadcasting and audio distribution activities'),
  ('60.10', 4, '60.1', 'Radio broadcasting and audio distribution activities'),
  ('60.2', 3, '60', 'Television programming, broadcasting and video distribution activities'),
  ('60.20', 4, '60.2', 'Television programming, broadcasting and video distribution activities'),
  ('60.3', 3, '60', 'News agency and other content distribution activities'),
  ('60.31', 4, '60.3', 'News agency activities'),
  ('60.39', 4, '60.3', 'Other content distribution activities'),
  ('61', 2, 'K', 'Telecommunication'),
  ('61.1', 3, '61', 'Wired, wireless, and satellite telecommunication activities'),
  ('61.10', 4, '61.1', 'Wired, wireless, and satellite telecommunication activities'),
  ('61.2', 3, '61', 'Telecommunication reselling activities and intermediation service activities for telecommunication'),
  ('61.20', 4, '61.2', 'Telecommunication reselling activities and intermediation service activities for telecommunication'),
  ('61.9', 3, '61', 'Other telecommunication activities'),
  ('61.90', 4, '61.9', 'Other telecommunication activities'),
  ('62', 2, 'K', 'Computer programming, consultancy and related activities'),
  ('62.1', 3, '62', 'Computer programming activities'),
  ('62.10', 4, '62.1', 'Computer programming activities'),
  ('62.2', 3, '62', 'Computer consultancy and computer facilities management activities'),
  ('62.20', 4, '62.2', 'Computer consultancy and computer facilities management activities'),
  ('62.9', 3, '62', 'Other information technology and computer service activities'),
  ('62.90', 4, '62.9', 'Other information technology and computer service activities'),
  ('63', 2, 'K', 'Computing infrastructure, data processing, hosting and other information service activities'),
  ('63.1', 3, '63', 'Computing infrastructure, data processing, hosting and related activities'),
  ('63.10', 4, '63.1', 'Computing infrastructure, data processing, hosting and related activities'),
  ('63.9', 3, '63', 'Web search portal activities and other information service activities'),
  ('63.91', 4, '63.9', 'Web search portal activities'),
  ('63.92', 4, '63.9', 'Other information service activities'),
  ('64', 2, 'L', 'Financial service activities, except insurance and pension funding'),
  ('64.1', 3, '64', 'Monetary intermediation'),
  ('64.11', 4, '64.1', 'Central banking'),
  ('64.19', 4, '64.1', 'Other monetary intermediation'),
  ('64.2', 3, '64', 'Activities of holding companies and financing conduits'),
  ('64.21', 4, '64.2', 'Activities of holding companies'),
  ('64.22', 4, '64.2', 'Activities of financing conduits'),
  ('64.3', 3, '64', 'Activities of trusts, funds and similar financial entities'),
  ('64.31', 4, '64.3', 'Activities of money market and non-money market investments funds'),
  ('64.32', 4, '64.3', 'Activities of trust, estate and agency accounts'),
  ('64.9', 3, '64', 'Other financial service activities, except insurance and pension funding'),
  ('64.91', 4, '64.9', 'Financial leasing'),
  ('64.92', 4, '64.9', 'Other credit granting'),
  ('64.99', 4, '64.9', 'Other financial service activities, except insurance and pension funding n.e.c.'),
  ('65', 2, 'L', 'Insurance, reinsurance and pension funding, except compulsory social security'),
  ('65.1', 3, '65', 'Insurance'),
  ('65.11', 4, '65.1', 'Life insurance'),
  ('65.12', 4, '65.1', 'Non-life insurance'),
  ('65.2', 3, '65', 'Reinsurance'),
  ('65.20', 4, '65.2', 'Reinsurance'),
  ('65.3', 3, '65', 'Pension funding'),
  ('65.30', 4, '65.3', 'Pension funding'),
  ('66', 2, 'L', 'Activities auxiliary to financial services and insurance activities'),
  ('66.1', 3, '66', 'Activities auxiliary to financial services, except insurance and pension funding'),
  ('66.11', 4, '66.1', 'Administration of financial markets'),
  ('66.12', 4, '66.1', 'Security and commodity contracts brokerage'),
  ('66.19', 4, '66.1', 'Other activities auxiliary to financial services, except insurance and pension funding'),
  ('66.2', 3, '66', 'Activities auxiliary to insurance and pension funding'),
  ('66.21', 4, '66.2', 'Risk and damage evaluation'),
  ('66.22', 4, '66.2', 'Activities of insurance agents and brokers'),
  ('66.29', 4, '66.2', 'Activities auxiliary to insurance and pension funding n.e.c.'),
  ('66.3', 3, '66', 'Fund management activities'),
  ('66.30', 4, '66.3', 'Fund management activities'),
  ('68', 2, 'M', 'Real estate activities'),
  ('68.1', 3, '68', 'Real estate activities with own property and development of building projects'),
  ('68.11', 4, '68.1', 'Buying and selling of own real estate'),
  ('68.12', 4, '68.1', 'Development of building projects'),
  ('68.2', 3, '68', 'Rental and operating of own or leased real estate'),
  ('68.20', 4, '68.2', 'Rental and operating of own or leased real estate'),
  ('68.3', 3, '68', 'Real estate activities on a fee or contract basis'),
  ('68.31', 4, '68.3', 'Intermediation service activities for real estate activities'),
  ('68.32', 4, '68.3', 'Other real estate activities on a fee or contract basis'),
  ('69', 2, 'N', 'Legal and accounting activities'),
  ('69.1', 3, '69', 'Legal activities'),
  ('69.10', 4, '69.1', 'Legal activities'),
  ('69.2', 3, '69', 'Accounting, bookkeeping and auditing activities; tax consultancy'),
  ('69.20', 4, '69.2', 'Accounting, bookkeeping and auditing activities; tax consultancy'),
  ('70', 2, 'N', 'Activities of head offices and management consultancy'),
  ('70.1', 3, '70', 'Activities of head offices'),
  ('70.10', 4, '70.1', 'Activities of head offices'),
  ('70.2', 3, '70', 'Business and other management consultancy activities'),
  ('70.20', 4, '70.2', 'Business and other management consultancy activities'),
  ('71', 2, 'N', 'Architectural and engineering activities; technical testing and analysis'),
  ('71.1', 3, '71', 'Architectural and engineering activities and related technical consultancy'),
  ('71.11', 4, '71.1', 'Architectural activities'),
  ('71.12', 4, '71.1', 'Engineering activities and related technical consultancy'),
  ('71.2', 3, '71', 'Technical testing and analysis'),
  ('71.20', 4, '71.2', 'Technical testing and analysis'),
  ('72', 2, 'N', 'Scientific research and development'),
  ('72.1', 3, '72', 'Research and experimental development on natural sciences and engineering'),
  ('72.10', 4, '72.1', 'Research and experimental development on natural sciences and engineering'),
  ('72.2', 3, '72', 'Research and experimental development on social sciences and humanities'),
  ('72.20', 4, '72.2', 'Research and experimental development on social sciences and humanities'),
  ('73', 2, 'N', 'Activities of advertising, market research and public relations'),
  ('73.1', 3, '73', 'Advertising'),
  ('73.11', 4, '73.1', 'Activities of advertising agencies'),
  ('73.12', 4, '73.1', 'Media representation'),
  ('73.2', 3, '73', 'Market research and public opinion polling'),
  ('73.20', 4, '73.2', 'Market research and public opinion polling'),
  ('73.3', 3, '73', 'Public relations and communication activities'),
  ('73.30', 4, '73.3', 'Public relations and communication activities'),
  ('74', 2, 'N', 'Other professional, scientific and technical activities'),
  ('74.1', 3, '74', 'Specialised design activities'),
  ('74.11', 4, '74.1', 'Industrial product and fashion design activities'),
  ('74.12', 4, '74.1', 'Graphic design and visual communication activities'),
  ('74.13', 4, '74.1', 'Interior design activities'),
  ('74.14', 4, '74.1', 'Other specialised design activities'),
  ('74.2', 3, '74', 'Photographic activities'),
  ('74.20', 4, '74.2', 'Photographic activities'),
  ('74.3', 3, '74', 'Translation and interpretation activities'),
  ('74.30', 4, '74.3', 'Translation and interpretation activities'),
  ('74.9', 3, '74', 'Other professional, scientific and technical activities n.e.c.'),
  ('74.91', 4, '74.9', 'Patent brokering and marketing service activities'),
  ('74.99', 4, '74.9', 'All other professional, scientific and technical activities n.e.c.'),
  ('75', 2, 'N', 'Veterinary activities'),
  ('75.0', 3, '75', 'Veterinary activities'),
  ('75.00', 4, '75.0', 'Veterinary activities'),
  ('77', 2, 'O', 'Rental and leasing activities'),
  ('77.1', 3, '77', 'Rental and leasing of motor vehicles'),
  ('77.11', 4, '77.1', 'Rental and leasing of cars and light motor vehicles'),
  ('77.12', 4, '77.1', 'Rental and leasing of trucks'),
  ('77.2', 3, '77', 'Rental and leasing of personal and household goods'),
  ('77.21', 4, '77.2', 'Rental and leasing of recreational and sports goods'),
  ('77.22', 4, '77.2', 'Rental and leasing of other personal and household goods'),
  ('77.3', 3, '77', 'Rental and leasing of other machinery, equipment and tangible goods'),
  ('77.31', 4, '77.3', 'Rental and leasing of agricultural machinery and equipment'),
  ('77.32', 4, '77.3', 'Rental and leasing of construction and civil engineering machinery and equipment'),
  ('77.33', 4, '77.3', 'Rental and leasing of office machinery, equipment and computers'),
  ('77.34', 4, '77.3', 'Rental and leasing of water transport equipment'),
  ('77.35', 4, '77.3', 'Rental and leasing of air transport equipment'),
  ('77.39', 4, '77.3', 'Rental and leasing of other machinery, equipment and tangible goods n.e.c.'),
  ('77.4', 3, '77', 'Leasing of intellectual property and similar products, except copyrighted works'),
  ('77.40', 4, '77.4', 'Leasing of intellectual property and similar products, except copyrighted works'),
  ('77.5', 3, '77', 'Intermediation service activities for rental and leasing of tangible goods and non-financial intangible assets'),
  ('77.51', 4, '77.5', 'Intermediation service activities for rental and leasing of cars, motorhomes and trailers'),
  ('77.52', 4, '77.5', 'Intermediation service activities for rental and leasing of other tangible goods and non-financial intangible assets'),
  ('78', 2, 'O', 'Employment activities'),
  ('78.1', 3, '78', 'Activities of employment placement agencies'),
  ('78.10', 4, '78.1', 'Activities of employment placement agencies'),
  ('78.2', 3, '78', 'Temporary employment agency activities and other human resource provisions'),
  ('78.20', 4, '78.2', 'Temporary employment agency activities and other human resource provisions'),
  ('79', 2, 'O', 'Travel agency, tour operator and other reservation service and related activities'),
  ('79.1', 3, '79', 'Travel agency and tour operator activities'),
  ('79.11', 4, '79.1', 'Travel agency activities'),
  ('79.12', 4, '79.1', 'Tour operator activities'),
  ('79.9', 3, '79', 'Other reservation service and related activities'),
  ('79.90', 4, '79.9', 'Other reservation service and related activities'),
  ('80', 2, 'O', 'Investigation and security activities'),
  ('80.0', 3, '80', 'Investigation and security activities'),
  ('80.01', 4, '80.0', 'Investigation and private security activities'),
  ('80.09', 4, '80.0', 'Security activities n.e.c.'),
  ('81', 2, 'O', 'Services to buildings and landscape activities'),
  ('81.1', 3, '81', 'Combined facilities support activities'),
  ('81.10', 4, '81.1', 'Combined facilities support activities'),
  ('81.2', 3, '81', 'Cleaning activities'),
  ('81.21', 4, '81.2', 'General cleaning of buildings'),
  ('81.22', 4, '81.2', 'Other building and industrial cleaning activities'),
  ('81.23', 4, '81.2', 'Other cleaning activities'),
  ('81.3', 3, '81', 'Landscape service activities'),
  ('81.30', 4, '81.3', 'Landscape service activities'),
  ('82', 2, 'O', 'Office administrative, office support and other business support activities'),
  ('82.1', 3, '82', 'Office administrative and support activities'),
  ('82.10', 4, '82.1', 'Office administrative and support activities'),
  ('82.2', 3, '82', 'Activities of call centres'),
  ('82.20', 4, '82.2', 'Activities of call centres'),
  ('82.3', 3, '82', 'Organisation of conventions and trade shows'),
  ('82.30', 4, '82.3', 'Organisation of conventions and trade shows'),
  ('82.4', 3, '82', 'Intermediation service activities for business support service activities n.e.c.'),
  ('82.40', 4, '82.4', 'Intermediation service activities for business support service activities n.e.c.'),
  ('82.9', 3, '82', 'Business support service activities n.e.c.'),
  ('82.91', 4, '82.9', 'Activities of collection agencies and credit bureaus'),
  ('82.92', 4, '82.9', 'Packaging activities'),
  ('82.99', 4, '82.9', 'Other business support service activities n.e.c.'),
  ('84', 2, 'P', 'Public administration and defence; compulsory social security'),
  ('84.1', 3, '84', 'Administration of the State and the economic, social and environmental policies of the community'),
  ('84.11', 4, '84.1', 'General public administration activities'),
  ('84.12', 4, '84.1', 'Regulation of health care, education, cultural services and other social services'),
  ('84.13', 4, '84.1', 'Regulation of and contribution to more efficient operation of businesses'),
  ('84.2', 3, '84', 'Provision of services to the community as a whole'),
  ('84.21', 4, '84.2', 'Foreign affairs'),
  ('84.22', 4, '84.2', 'Defence activities'),
  ('84.23', 4, '84.2', 'Justice and judicial activities'),
  ('84.24', 4, '84.2', 'Public order and safety activities'),
  ('84.25', 4, '84.2', 'Fire service activities'),
  ('84.3', 3, '84', 'Compulsory social security activities'),
  ('84.30', 4, '84.3', 'Compulsory social security activities'),
  ('85', 2, 'Q', 'Education'),
  ('85.1', 3, '85', 'Pre-primary education'),
  ('85.10', 4, '85.1', 'Pre-primary education'),
  ('85.2', 3, '85', 'Primary education'),
  ('85.20', 4, '85.2', 'Primary education'),
  ('85.3', 3, '85', 'Secondary and post-secondary non-tertiary education'),
  ('85.31', 4, '85.3', 'General secondary education'),
  ('85.32', 4, '85.3', 'Vocational secondary education'),
  ('85.33', 4, '85.3', 'Post-secondary non-tertiary education'),
  ('85.4', 3, '85', 'Tertiary education'),
  ('85.40', 4, '85.4', 'Tertiary education'),
  ('85.5', 3, '85', 'Other education'),
  ('85.51', 4, '85.5', 'Sports and recreation education'),
  ('85.52', 4, '85.5', 'Cultural education'),
  ('85.53', 4, '85.5', 'Driving school activities'),
  ('85.59', 4, '85.5', 'Other education n.e.c.'),
  ('85.6', 3, '85', 'Educational support activities'),
  ('85.61', 4, '85.6', 'Intermediation service activities for courses and tutors'),
  ('85.69', 4, '85.6', 'Educational support activities n.e.c.'),
  ('86', 2, 'R', 'Human health activities'),
  ('86.1', 3, '86', 'Hospital activities'),
  ('86.10', 4, '86.1', 'Hospital activities'),
  ('86.2', 3, '86', 'Medical and dental practice activities'),
  ('86.21', 4, '86.2', 'General medical practice activities'),
  ('86.22', 4, '86.2', 'Medical specialists activities'),
  ('86.23', 4, '86.2', 'Dental practice care activities'),
  ('86.9', 3, '86', 'Other human health activities'),
  ('86.91', 4, '86.9', 'Diagnostic imaging services and medical laboratory activities'),
  ('86.92', 4, '86.9', 'Patient transportation by ambulance'),
  ('86.93', 4, '86.9', 'Activities of psychologists and psychotherapists, except medical doctors'),
  ('86.94', 4, '86.9', 'Nursing and midwifery activities'),
  ('86.95', 4, '86.9', 'Physiotherapy activities'),
  ('86.96', 4, '86.9', 'Traditional, complementary and alternative medicine activities'),
  ('86.97', 4, '86.9', 'Intermediation service activities for medical, dental and other human health services'),
  ('86.99', 4, '86.9', 'Other human health activities n.e.c.'),
  ('87', 2, 'R', 'Residential care activities'),
  ('87.1', 3, '87', 'Residential nursing care activities'),
  ('87.10', 4, '87.1', 'Residential nursing care activities'),
  ('87.2', 3, '87', 'Residential care activities for persons living with or having a diagnosis of a mental illness or substance abuse'),
  ('87.20', 4, '87.2', 'Residential care activities for persons living with or having a diagnosis of a mental illness or substance abuse'),
  ('87.3', 3, '87', 'Residential care activities for older persons or persons with physical disabilities'),
  ('87.30', 4, '87.3', 'Residential care activities for older persons or persons with physical disabilities'),
  ('87.9', 3, '87', 'Other residential care activities'),
  ('87.91', 4, '87.9', 'Intermediation service activities for residential care activities'),
  ('87.99', 4, '87.9', 'Other residential care activities n.e.c.'),
  ('88', 2, 'R', 'Social work activities without accommodation'),
  ('88.1', 3, '88', 'Social work activities without accommodation for older persons or persons with disabilities'),
  ('88.10', 4, '88.1', 'Social work activities without accommodation for older persons or persons with disabilities'),
  ('88.9', 3, '88', 'Other social work activities without accommodation'),
  ('88.91', 4, '88.9', 'Child day-care activities'),
  ('88.99', 4, '88.9', 'Other social work activities without accommodation n.e.c.'),
  ('90', 2, 'S', 'Arts creation and performing arts activities'),
  ('90.1', 3, '90', 'Arts creation activities'),
  ('90.11', 4, '90.1', 'Literary creation and musical composition activities'),
  ('90.12', 4, '90.1', 'Visual arts creation activities'),
  ('90.13', 4, '90.1', 'Other arts creation activities'),
  ('90.2', 3, '90', 'Activities of performing arts'),
  ('90.20', 4, '90.2', 'Activities of performing arts'),
  ('90.3', 3, '90', 'Support activities to arts creation and performing arts'),
  ('90.31', 4, '90.3', 'Operation of arts facilities and sites'),
  ('90.39', 4, '90.3', 'Other support activities to arts and performing arts'),
  ('91', 2, 'S', 'Libraries, archives, museums and other cultural activities'),
  ('91.1', 3, '91', 'Library and archive activities'),
  ('91.11', 4, '91.1', 'Library activities'),
  ('91.12', 4, '91.1', 'Archive activities'),
  ('91.2', 3, '91', 'Museum, collection, historical site and monument activities'),
  ('91.21', 4, '91.2', 'Museum and collection activities'),
  ('91.22', 4, '91.2', 'Historical site and monument activities'),
  ('91.3', 3, '91', 'Conservation, restoration and other support activities for cultural heritage'),
  ('91.30', 4, '91.3', 'Conservation, restoration and other support activities for cultural heritage'),
  ('91.4', 3, '91', 'Botanical and zoological garden and nature reserve activities'),
  ('91.41', 4, '91.4', 'Botanical and zoological garden activities'),
  ('91.42', 4, '91.4', 'Nature reserve activities'),
  ('92', 2, 'S', 'Gambling and betting activities'),
  ('92.0', 3, '92', 'Gambling and betting activities'),
  ('92.00', 4, '92.0', 'Gambling and betting activities'),
  ('93', 2, 'S', 'Sports activities and amusement and recreation activities'),
  ('93.1', 3, '93', 'Sports activities'),
  ('93.11', 4, '93.1', 'Operation of sports facilities'),
  ('93.12', 4, '93.1', 'Activities of sports clubs'),
  ('93.13', 4, '93.1', 'Activities of fitness centres'),
  ('93.19', 4, '93.1', 'Sports activities n.e.c.'),
  ('93.2', 3, '93', 'Amusement and recreation activities'),
  ('93.21', 4, '93.2', 'Activities of amusement parks and theme parks'),
  ('93.29', 4, '93.2', 'Amusement and recreation activities n.e.c.'),
  ('94', 2, 'T', 'Activities of membership organisations'),
  ('94.1', 3, '94', 'Activities of business, employers and professional membership organisations'),
  ('94.11', 4, '94.1', 'Activities of business and employers membership organisations'),
  ('94.12', 4, '94.1', 'Activities of professional membership organisations'),
  ('94.2', 3, '94', 'Activities of trade unions'),
  ('94.20', 4, '94.2', 'Activities of trade unions'),
  ('94.9', 3, '94', 'Activities of other membership organisations'),
  ('94.91', 4, '94.9', 'Activities of religious organisations'),
  ('94.92', 4, '94.9', 'Activities of political organisations'),
  ('94.99', 4, '94.9', 'Activities of other membership organisations n.e.c.'),
  ('95', 2, 'T', 'Repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles'),
  ('95.1', 3, '95', 'Repair and maintenance of computers and communication equipment'),
  ('95.10', 4, '95.1', 'Repair and maintenance of computers and communication equipment'),
  ('95.2', 3, '95', 'Repair and maintenance of personal and household goods'),
  ('95.21', 4, '95.2', 'Repair and maintenance of consumer electronics'),
  ('95.22', 4, '95.2', 'Repair and maintenance of household appliances and home and garden equipment'),
  ('95.23', 4, '95.2', 'Repair and maintenance of footwear and leather goods'),
  ('95.24', 4, '95.2', 'Repair and maintenance of furniture and home furnishings'),
  ('95.25', 4, '95.2', 'Repair and maintenance of watches, clocks and jewellery'),
  ('95.29', 4, '95.2', 'Repair and maintenance of personal and household goods n.e.c.'),
  ('95.3', 3, '95', 'Repair and maintenance of motor vehicles and motorcycles'),
  ('95.31', 4, '95.3', 'Repair and maintenance of motor vehicles'),
  ('95.32', 4, '95.3', 'Repair and maintenance of motorcycles'),
  ('95.4', 3, '95', 'Intermediation service activities for repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles'),
  ('95.40', 4, '95.4', 'Intermediation service activities for repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles'),
  ('96', 2, 'T', 'Personal service activities'),
  ('96.1', 3, '96', 'Washing and cleaning of textile and fur products'),
  ('96.10', 4, '96.1', 'Washing and cleaning of textile and fur products'),
  ('96.2', 3, '96', 'Hairdressing, beauty treatment, day spa and similar activities'),
  ('96.21', 4, '96.2', 'Hairdressing and barber activities'),
  ('96.22', 4, '96.2', 'Beauty care and other beauty treatment activities'),
  ('96.23', 4, '96.2', 'Day spa, sauna and steam bath activities'),
  ('96.3', 3, '96', 'Funeral and related activities'),
  ('96.30', 4, '96.3', 'Funeral and related activities'),
  ('96.4', 3, '96', 'Intermediation service activities for personal services'),
  ('96.40', 4, '96.4', 'Intermediation service activities for personal services'),
  ('96.9', 3, '96', 'Other personal service activities'),
  ('96.91', 4, '96.9', 'Provision of domestic personal service activities'),
  ('96.99', 4, '96.9', 'Other personal service activities n.e.c.'),
  ('97', 2, 'U', 'Activities of households as employers of domestic personnel'),
  ('97.0', 3, '97', 'Activities of households as employers of domestic personnel'),
  ('97.00', 4, '97.0', 'Activities of households as employers of domestic personnel'),
  ('98', 2, 'U', 'Undifferentiated goods- and service-producing activities of private households for own use'),
  ('98.1', 3, '98', 'Undifferentiated goods-producing activities of private households for own use'),
  ('98.10', 4, '98.1', 'Undifferentiated goods-producing activities of private households for own use'),
  ('98.2', 3, '98', 'Undifferentiated service-producing activities of private households for own use'),
  ('98.20', 4, '98.2', 'Undifferentiated service-producing activities of private households for own use'),
  ('99', 2, 'V', 'Activities of extraterritorial organisations and bodies'),
  ('99.0', 3, '99', 'Activities of extraterritorial organisations and bodies'),
  ('99.00', 4, '99.0', 'Activities of extraterritorial organisations and bodies');
